dist: xenial
language: c

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-8-2018-q4-major
    - $HOME/nrf_sdk/15.3.0

addons:
  apt:
    packages:
    - dos2unix
    - python
    - python-pip

env:
  global:
    - GNU_INSTALL_ROOT="$HOME/gcc-arm-none-eabi-8-2018-q4-major/bin/"
    - NORDIC_SDK_PATH="$HOME/nrf_sdk/15.3.0"
    - PATH="$PATH:$HOME/gcc-arm-none-eabi-8-2018-q4-major/bin:$HOME/mergehex:$HOME/nrfjprog:$HOME/.local/bin"

  matrix:
    - BOARD=sparkfun-pro-mini
    - BOARD=sparkfun-pro-mini DEBUG=1
    - BOARD=mdk-usb-dongle
    - BOARD=mdk-usb-dongle DEBUG=1
    - BOARD=pca10059
    - BOARD=pca10059 DEBUG=1
    - BOARD=pca10056
    - BOARD=pca10056 DEBUG=1
    - BOARD=mdk
    - BOARD=mdk DEBUG=1
    - BOARD=particle-xenon
    - BOARD=particle-xenon DEBUG=1
    - BOARD=particle-boron
    - BOARD=particle-boron DEBUG=1
    - BOARD=particle-argon
    - BOARD=particle-argon DEBUG=1
    - BOARD=feather-express
    - BOARD=feather-express DEBUG=1

before_install:
  - chmod +x $TRAVIS_BUILD_DIR/.travis/before_install.sh
  - ln -s default_private.pem private.pem
  - ln -s default_dfu_public_key.c dfu_public_key.c

install:
  - $TRAVIS_BUILD_DIR/.travis/before_install.sh
  # Verify the arm-none-eabi-gcc binary is working correctly
  - arm-none-eabi-gcc --version
  # Verify mergehex is loaded into PATH
  - mergehex --version
  - pip install --user nrfutil

script:
  - make clean_build

deploy:
  provider: releases
  overwrite: true
  file_glob: true
  api_key:
    secure: OR1ON5GoqkkGPswHZsv1OX9WddNwtjOFpZ/6M4Yf0Ktwzbzpa5DUeydi6HZlLvgxN1PgA5+ImSVNgbKa7kV4d2I8WlCv9lFtb1KE+VqAunc+y+2IHHLa1cwPUkwjkB0OzoSUmixvgLvPsjRItABlk5qmbqZI+Kog9UvpxQUqMJNEdfLrVmHZ5vKRCwo/Xsvn/TLCix/0C72xuv0EzI4cnZLbl5WrIAmqNt3qA9AtAQz1tjTw8SMZohno+lqKj+3LzwYPkhaKBA0y1cgxkF4knGjlKEQ0B4hqan0+RpYrMLWu3IvjvT1O01HPWf8q860DTb3QE2GwaLbWUo6RZNWxFILHLcz2jmA1jeXqs1Q79+RSOBOuN/FYC/u567FSeOYWYoGkUv9OhUwhA58Dg4stEhv11O12PIB/TFe/6Hg5ImtWY4nbQ8h9qu2p9FE1kQ5q8K07uaFwOJ89C8RpEtt6CAJOmKo06ezaaUgmcItQ6EjRPjyauj53bQ04to1IpW6C8p2eWC+ZBCyA3pqRWs8LA7MnMG/IT6xiJfDvoVBo+/B8vDSZECCP72jFYclMHk9ksWNMxuepBPJxYlPn7+vhspJiF9CvKNuug/2oMi9luuST17lvo4P04txVlvzo0xSOOYODMZipQ+k3d1Udei1cCXST/STwr/HLJ8QnCNQKTaU=
  file: "$TRAVIS_BUILD_DIR/_build_$BOARD/*s140.*"
  skip_cleanup: true
  draft: true
  on:
    repo: charlesportwoodii/kaidyth_nrf52_bootloader
    tags: true
    condition: $DEBUG=0
